on:
  workflow_dispatch:

name: Jest Tests

jobs:
  concurrent-test:
    name: Jest Tests (Concurrent)
    runs-on: warp-ubuntu-latest-x64-4x
    defaults:
      run:
        working-directory: examples/jest

    strategy:
      fail-fast: false
      matrix:
        shardCount: [10]
        shardIdx: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci

      - name: Generate 100 Jest test files
        run: bash ./generate-test-files.sh 100

      - name: Run Jest tests
        run: npx jest --shard=${{ matrix.shardIdx }}/${{ matrix.shardCount }}

  sequential-test:
    name: Jest Tests (Sequential)
    runs-on: warp-ubuntu-latest-x64-4x
    defaults:
      run:
        working-directory: examples/jest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
        
      - name: Generate 100 Jest test files
        run: bash ./generate-test-files.sh 100

      - name: Run Jest tests
        run: npx jest
