name: Playwright Tests (With Container)
on: workflow_dispatch

jobs:
  concurrent-tests:
    name: Playwright Tests (Concurrent)
    runs-on: warp-ubuntu-latest-x64-4x
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy
    defaults:
      run:
        working-directory: examples/playwright

    strategy:
      fail-fast: false
      matrix:
        shardCount: [10]
        shardIndex: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci

      - name: Run Playwright tests
        run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardCount }}

  sequential-tests:
    name: Playwright Tests (Sequential)
    runs-on: warp-ubuntu-latest-x64-4x
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy
    defaults:
      run:
        working-directory: examples/playwright

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci

      - name: Run Playwright tests
        run: npx playwright test
